services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    develop:
      watch:
        - action: rebuild
          path: ./src
